# Welcome to Numpy

In [1]:
import sys

import numpy as np

In [2]:
myarr = np.array([[1,2,3,4,5,61234,235]], np.int64)

In [3]:
myarr[0]

array([    1,     2,     3,     4,     5, 61234,   235])

In [4]:
myarr[0,1]

np.int64(2)

In [5]:
myarr.shape

(1, 7)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,3] = 199

In [8]:
myarr

array([[    1,     2,     3,   199,     5, 61234,   235]])

In [10]:
larray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
larray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
larray.shape

(3, 3)

In [14]:
larray.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [15]:
larray.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
larray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
larray.size

9

In [18]:
np.array({34,36,12,12})

array({34, 36, 12}, dtype=object)

this is not very efficient in numpy therefore we dont use it very often with numpy

In [19]:
zeros = np.zeros((2,4))

In [20]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
ones = np.ones((4,2))

In [22]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
r = np.arange(1,11)

In [24]:
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
lspace = np.linspace(0,10,6)

In [34]:
lspace

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [39]:
ept = np.empty((4,3))

In [40]:
ept

array([[1.09368342e-311, 2.76676762e-322, 0.00000000e+000],
       [0.00000000e+000, 1.11260619e-306, 1.16095484e-028],
       [2.17237425e-153, 1.13224202e+277, 4.02994294e-144],
       [2.91237123e+257, 4.71294503e+257, 1.48169336e+295]])

In [41]:
np.empty_like(lspace)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [42]:
diag1 = np.identity(5)

In [43]:
diag1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
larray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
larray.sum(axis=0)

array([12, 15, 18])

In [48]:
larray.sum(axis=1)

array([ 6, 15, 24])

In [49]:
larray.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [50]:
larray.__invert__()

array([[ -2,  -3,  -4],
       [ -5,  -6,  -7],
       [ -8,  -9, -10]])

In [52]:
larray.flat

In [53]:
for item in larray.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [54]:
larray.ndim

2

In [55]:
larray.nbytes

72

In [56]:
one = np.array([1,4,12,41,123,568,5])

In [57]:
one.argmax()

np.int64(5)

In [58]:
one.argmin()

np.int64(0)

In [59]:
one.argsort() # returns array of index in ascending order

array([0, 1, 6, 2, 3, 4, 5])

In [60]:
ar = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [61]:
ar.argmin()

np.int64(8)

In [62]:
ar.argmax()

np.int64(6)

In [63]:
ar.argmax(axis=0)

array([2, 1, 1])

In [65]:
ar.argmax(axis=1)

array([2, 2, 0])

In [66]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [67]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [68]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [69]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [70]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [71]:
np.count_nonzero(ar)

np.int64(8)

In [74]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [75]:
py_ar = [0,4,55,2]

In [76]:
np_ar = np.array(py_ar)

In [77]:
sys.getsizeof(1)*len(py_ar)

112

In [78]:
np_ar.itemsize * np_ar.size

32