In [1]:
import numpy as np
n = [6,7,8]
n[0:1]

[6]

In [2]:
n[-1]

8

In [3]:
a = np.array([6,7,8])

In [4]:
a[0:2]

array([6, 7])

In [5]:
a[-1]

np.int64(8)

In [8]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [9]:
a[1,2]

np.int64(3)

In [10]:
a[0:2,2] #slicing

array([8, 3])

In [11]:
a[-1]

array([9, 3, 2])

In [12]:
a[-1,0:2]

array([9, 3])

In [17]:
a[:,1:3] # : means all rows similar to 0:3

array([[7, 8],
       [2, 3],
       [3, 2]])

In [18]:
for row in a: # for normal printing an array
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [20]:
for cell in a.flat: # flattens the array into a single dimension array
    print(cell)

6
7
8
1
2
3
9
3
2


In [22]:
a = np.arange(6).reshape(3,2)

In [23]:
b = np.arange(6,12).reshape(3,2)

In [25]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [27]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [28]:
np.vstack((b,a))

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

In [29]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [31]:
a = np.arange(30).reshape(2,15)

In [32]:
np.hsplit(a,3) # splits into 3 different matrix that are sliced vertically but move horizontally

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [33]:
np.vsplit(a,2) # splits into 2 arrays slicinf a line horizontally but moves up to down so called vertically

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [34]:
a = np.arange(12).reshape(3,4)

In [35]:
b = a>4 #checks for condition and returns true or fal se as a matrix
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
a[b] # returns positive values of a according to b

array([ 5,  6,  7,  8,  9, 10, 11])

In [37]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])